name: Initialize Repository

on:
  workflow_dispatch:    # 手动触发，可用于仓库首次初始化

jobs:
  init:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repository
        uses: actions/checkout@v3

      - name: Set repository variables
        run: |
          # 从环境变量 GITHUB_REPOSITORY 中提取仓库名称（格式为 owner/repo）
          REPO_FULL="${GITHUB_REPOSITORY}"
          REPO_NAME="${REPO_FULL#*/}"
          # 将横杠替换为下划线
          UNDERSCORE_REPO_NAME=$(echo "$REPO_NAME" | tr '-' '_')
          echo "REPO_NAME=${REPO_NAME}" >> $GITHUB_ENV
          echo "UNDERSCORE_REPO_NAME=${UNDERSCORE_REPO_NAME}" >> $GITHUB_ENV
          echo "Repository name: $REPO_NAME"
          echo "Repository underscore name: $UNDERSCORE_REPO_NAME"

      - name: Update README.md
        run: |
          # 替换 README.md 中的内容
          sed -i.bak "s/nonebot-plugin-PPPPP/${REPO_NAME}/g" README.md
          sed -i.bak "s/nonebot_plugin_ppppp/${UNDERSCORE_REPO_NAME}/g" README.md

      - name: Update pyproject.toml
        run: |
          # 替换 pyproject.toml 中的内容
          sed -i.bak "s/nonebot-plugin-template/${REPO_NAME}/g" pyproject.toml
          sed -i.bak "s/nonebot_plugin_template/${UNDERSCORE_REPO_NAME}/g" pyproject.toml

      - name: Rename plugin folder
        run: |
          if [ -d "nonebot_plugin_template" ]; then
            mv nonebot_plugin_template "${UNDERSCORE_REPO_NAME}"
          else
            echo "Directory nonebot_plugin_template not found."
          fi

      - name: Commit and push changes
        run: |
          git config user.name "github-actions"
          git config user.email "github-actions@github.com"
          git add .
          git commit -m "Initialize repository variables"
          git push