name: Ruff Lint

on:
  push:
    branches:
      - master
  pull_request:
    paths:
      - "tests/**"
      - ".github/workflows/ruff.yml"
      - "pyproject.toml"
      - "uv.lock"

jobs:
  ruff:
    name: Ruff Lint
    runs-on: ubuntu-latest
    concurrency:
      group: pyright-${{ github.ref }}
      cancel-in-progress: true

    steps:
      - uses: actions/checkout@v4

      - name: Run Ruff Lint
        uses: astral-sh/ruff-action@v3