name: Test Load

on:
  push:
    branches:
      - '*'

jobs:
  build:
    runs-on: ubuntu-latest
    strategy:
      matrix:
        python-version:
          - "3.10"
          - "3.11"
          - "3.12"

    steps:
    - name: Checkout repository
      uses: actions/checkout@v2
    
    - name: Install uv and set the python version
      uses: astral-sh/setup-uv@v5
      with:
        python-version: ${{ matrix.python-version }}

    - name: Install dependencies
      run: |
        uv venv
        source .venv/bin/activate
        uv sync --group dev

    - name: Load Plugin
      run: |
        python -c "
        import nonebot;
        import tomllib;
        from pathlib import Path;
        nonebot.init();
        data = tomllib.loads(Path("pyproject.toml").read_text(encoding="u8"));
        nonebot_data = data.get("tool", {}).get("nonebot")
        assert nonebot_data is not None, "Cannot find '[tool.nonebot]' in project toml file!";
        assert isinstance(nonebot_data, dict), "[tool.nonebot] must be a table";
        adapters = nonebot_data.get("adapters", []);
        for ad in adapters:
            assert isinstance(ad, dict), "adapter info must be a table"
            assert (md := ad.get("module_name")), "adapter must have a module_name"
            driver.register_adapter(importlib.import_module(md).Adapter);
        nonebot.get_driver().register_adapter(Adapter);
        nonebot.load_from_toml('pyproject.toml')
        "
